### ISSUE TITLE
[BUG] Module Python manquant 

### ISSUE THREAD

**Issue by Aioniostheos** [MaximilianTyan/GaliTime_Photomaton#1]
Lors de l'installation (avec le script `install.sh`), le module `pycups` ne s'installe pas. Cela cause une erreur au lancement du Photomaton.

Cela peut être facilement résolu en installant manuellement le module dans l'environnement virtuel :
```
source env/bin/activate
pip install pycups
deactivate
```

**Comment by MaximilianTyan** [comment]
Essaie d'exécuter `install.sh` et poste l'output de ton terminal ici

**Comment by Aioniostheos** [comment]
L'erreur provient de :
Installing python packages ...
python3: can't open file '/home/galitime/GaliTime_Photomaton/pip': [Errno 2] No such file or directory

Manuellement, j'arrive à utiliser pip mais le script n'y parvient pas.

**Comment by Aioniostheos** [comment]
Il faudrait remplace la destination par :
/home/galitime/GaliTime_Photomaton/env/bin/pip

**Comment by MaximilianTyan** [comment]
Je viens de trouver le problème, il faut que la commande soit `python3 -m pip`, sinon python ne comprend pas que c'est le module pip qu'il faut executed et pas un fichier nommé pip

**Comment by Aioniostheos** [comment]
Le module pycups s'installe correctement.
