### ISSUE TITLE
[BUG] Erreur à l'impression : Fichier manquant

### ISSUE THREAD

**Issue by Aioniostheos** [MaximilianTyan/GaliTime_Photomaton#2]
Lorsqu'on essaye d'imprimer la photo, une erreur est signalée concernant un fichier manquant.

A priori, lors de l'impression, le fichier de la photo "n'existe plus".  Le fichier existe bien mais l'erreur est déclenchée par `os.path.exists`.
Selon la documentation Python, `os.path.exists` peut retourner `False` si le programme ne peut pas accéder au fichier.
Si on retire les lignes de vérifications du chemin d'accès (lignes 73 et 74 de `peripherals/printer.py`), l'impression fonctionne correctement.

Logs :
```
[INFO] (controlpage) 256 : Printing file /home/.../last_photo.jpg
[ERROR] (controlpage) 261 : Printing error : Image file not found.
```

**Comment by Aioniostheos** [comment]
La ligne 73 de `peripherals/printer.py` devrait être changée de `if os.path.exists(filepath)` en `if not os.path.exists(filepath)`.

**Comment by MaximilianTyan** [comment]
Erreur bête, je le fixe au plus vite

**Comment by Aioniostheos** [comment]
L'impression fonctionne correctement.
